# example commands:
# snakemake --configfile example/config.yaml --dry-run
# snakemake --configfile example/config.yaml --use-conda --conda-frontend mamba --resources mem_mb=40_000 -j 28 > log.txt 2>&1

# input
rna_samples: example/rna_samples.tsv
rna_tpms: example/GRCz11-TPM.tsv
rna_counts: example/GRCz11-counts.tsv

atac_samples: example/atac_samples.tsv
atac_counts: example/GRCz11_raw.tsv

genome: GRCz11  # genomepy install GRCz11 --annotation
# genomes_dir:  # where to search for genomes (default: $HOME/.local/share/genomes)

# output
result_dir: example/outdir

# what analysis to run.
# format: column_group2_group1
# column must be present in both samples files
# groups must be present in this column
# for RNA-seq, each group must have 2 or more samples (for DESeq2)
contrasts:
  - "anansnake_group2_group1"
  - "anansnake_group1_group2"


# optional settings


# gimme
database: gimme.vertebrate.v5.0  # options: https://gimmemotifs.readthedocs.io/en/master/overview.html#motif-databases
tmp_dir: example/tmp  # intermediate output location, can be None
keep_tmp_data: true  # keep the orthofinder output (in the tmp_dir)?

# use descriptive names in the sample.tsv
use_descriptive_names: false  # true for seq2science > 0.7.1

# ANANSE binding
jaccard: 0.2  # default: 0.1

# ANANSE influence
edges: 500_000  # default: 500_000
padj: 0.05

# ANANSE plot
plot_type: "png"
