# example command
# snakemake --configfile config.yaml --use-conda -j 1 -n

# input
rna_samples: example/rna_samples.tsv
rna_tpms: example/GRCz11-TPM.tsv
rna_counts: example/GRCz11-counts.tsv

atac_samples: example/atac_samples.tsv
atac_counts: example/GRCz11_raw.tsv

genome: GRCz11  # genomepy install GRCz11 --annotation
# genomes_dir:  # where to search for/store genomes (default: $HOME/.local/share/genomes)

# output
result_dir: example/outdir

# what analysis to run.
# format: column_group2_group1
# column must be present in both samples files
# groups must be present in this column
# for RNA-seq, each group must have 2 or more samples (for DESeq2)
contrasts:
  - "anansnake_group2_group1"
  - "anansnake_group1_group2"

# optional settings

# ANANSE binding
jaccard: 0.2  # default: 0.1

# ANANSE influence
edges: 500_000  # default: 100_000
padj: 0.05

# ANANSE plot
plot_type: "png"
